services:
    ting_metadatarepository:
        class: CCMBenchmark\Ting\MetadataRepository
        arguments: ["@=service('ting_metadatafactory')"]

    ting_queryfactory:
        class: CCMBenchmark\Ting\Query\QueryFactory

    ting_driverlogger:
        synthetic: true

    ting_connectionpool:
        class: CCMBenchmark\Ting\ConnectionPool

    ting_unitofwork:
        class: CCMBenchmark\Ting\UnitOfWork
        arguments: ["@=service('ting_connectionpool')", "@=service('ting_metadatarepository')", "@=service('ting_queryfactory')"]

    ting_hydrator:
        class: CCMBenchmark\Ting\Repository\Hydrator
        arguments: ["@=service('ting_metadatarepository')", "@=service('ting_unitofwork')"]

    ting_collectionfactory:
        class: CCMBenchmark\Ting\Repository\CollectionFactory
        arguments: ["@=service('ting_hydrator')"]

    ting_cache:
        class: CCMBenchmark\Ting\Cache\Memcached

    ting_driver_data_collector:
        class: CCMBenchmark\TingBundle\DataCollector\TingDriverDataCollector
        tags:
            - {name: data_collector, template:"TingBundle:Collector:driverCollector", id:"ting_driver"}

    ting_cache_data_collector:
        class: CCMBenchmark\TingBundle\DataCollector\TingCacheDataCollector
        tags:
            - {name: data_collector, template:"TingBundle:Collector:cacheCollector", id:"ting_cache"}

    ting:
        class: CCMBenchmark\Ting\Repository\RepositoryFactory
        arguments:
            - "@=service('ting_connectionpool')"
            - "@=service('ting_metadatarepository')"
            - "@=service('ting_queryfactory')"
            - "@=service('ting_collectionfactory')"
            - "@=service('ting_unitofwork')"
            - "@=service('ting_cache')"

    ting.metadata_warmer:
        class: CCMBenchmark\TingBundle\Cache\MetadataWarmer
        arguments:
            - "@=service('service_container')"
        tags:
            - {name: kernel.cache_warmer, priority:0}