services:
    ting.metadatarepository:
        class: CCMBenchmark\Ting\MetadataRepository
        arguments:
            - "@ting.serializerfactory"

    ting.serializerfactory:
        class: CCMBenchmark\Ting\Serializer\SerializerFactory

    ting.queryfactory:
        class: CCMBenchmark\Ting\Query\QueryFactory

    ting.driverlogger:
        synthetic: true

    ting.connectionpool:
        class: CCMBenchmark\Ting\ConnectionPool

    ting.unitofwork:
        class: CCMBenchmark\Ting\UnitOfWork
        arguments:
            - "@ting.connectionpool"
            - "@ting.metadatarepository"
            - "@ting.queryfactory"

    ting.hydrator:
        class: CCMBenchmark\Ting\Repository\Hydrator
        calls:
            - [setMetadataRepository, ["@ting.metadatarepository"]]
            - [setUnitOfWork, ["@ting.unitofwork"]]
        shared: false

    ting.hydrator_single_object:
        class: CCMBenchmark\Ting\Repository\HydratorSingleObject
        calls:
            - [setMetadataRepository, ["@ting.metadatarepository"]]
            - [setUnitOfWork, ["@ting.unitofwork"]]
        shared: false

    ting.collectionfactory:
        class: CCMBenchmark\Ting\Repository\CollectionFactory
        arguments:
            - "@ting.metadatarepository"
            - "@ting.unitofwork"
            - "@ting.hydrator"

    ting.cache:
        class: CCMBenchmark\Ting\Cache\Cache

    ting.cache.void:
        class: Doctrine\Common\Cache\VoidCache

    ting.driver_data_collector:
        class: CCMBenchmark\TingBundle\DataCollector\TingDriverDataCollector
        tags:
            - {name: data_collector, template:"TingBundle:Collector:driverCollector", id:"ting.driver"}

    ting.cache_data_collector:
        class: CCMBenchmark\TingBundle\DataCollector\TingCacheDataCollector
        tags:
            - {name: data_collector, template:"TingBundle:Collector:cacheCollector", id:"ting.cache"}

    ting:
        class: CCMBenchmark\Ting\Repository\RepositoryFactory
        arguments:
            - "@ting.connectionpool"
            - "@ting.metadatarepository"
            - "@ting.queryfactory"
            - "@ting.collectionfactory"
            - "@ting.unitofwork"
            - "@ting.cache"
            - "@ting.serializerfactory"

    ting.metadata_warmer:
        class: CCMBenchmark\TingBundle\Cache\MetadataWarmer
        arguments:
            - "@service_container"
        tags:
            - {name: kernel.cache_warmer, priority:0}
