name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.2
          - 8.3
        deps:
          - highest
          - lowest
        composer:
          - v2
    name: Unit tests (PHP ${{ matrix.php }}, composer ${{ matrix.composer }}, ${{ matrix.deps }} dependencies)
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: bcmath, bz2, gettext, mbstring, memcached, mcrypt, mysqli, opcache, pdo_mysql, zip, pdo, intl, json, pdo_pgsql, pgsql, session, simplexml, xml
          tools: "composer:${{ matrix.composer }}, pecl"

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run Atoum tests
        run: php vendor/bin/atoum
